package main

import (
	// "math/rand"
	"crypto/rand"
	"fmt"
	"math/big"
)

func main() {
	fmt.Println("Welcome to maths in Golang")

	var myNumberOne int = 2
	var myNumberTwo float64 = 4.5

	// fmt.Println("Addition: ", myNumberOne + myNumberTwo) // Error: invalid operation: myNumberOne + myNumberTwo (mismatched types int and float64)
	fmt.Println("Addition: ", myNumberOne + int(myNumberTwo))

	// RANDOM NUMBER -> 1. Generated by MATH package (math/rand) 2. Generated by CRYPTO package (crypto/rand)
	// 1. MATH PACKAGE
	// fmt.Println("Random Number: ", math.rand.Intn(5)) // 0 to 4 -> 5 is exclusive, 
	// we can also use Rand.Seed() to generate random number and put time.Now().UnixNano() as argument

	// 2. CRYPTO PACKAGE
	myRN, _ := rand.Int(rand.Reader, big.NewInt(5))
	fmt.Println("Random Number: ", myRN) 
	
}